// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2025-2025, The OpenROAD Authors

// Tcl registration bootstrap for ipl.
//
// initIntegratedPlacer() is called once from OpenRoad::init() after the
// OpenRoad object is fully constructed.  It:
//   1. Calls Ipl_Init() (generated by SWIG from ipl.i) to register the
//      raw C-level Tcl commands.
//   2. Evaluates the encoded ipl.tcl script (encoded by the CMake
//      messages() / swig_lib() machinery) to define the higher-level
//      Tcl command wrappers.

#include "ipl/MakeIntegratedPlacer.h"

#include "tcl.h"
#include "utl/decode.h"

// Generated by SWIG from src/ipl.i
extern "C" {
extern int Ipl_Init(Tcl_Interp* interp);
}

namespace ipl {

// ipl.tcl encoded as null-terminated string array by the CMake swig_lib rule.
extern const char* ipl_tcl_inits[];

void initIntegratedPlacer(Tcl_Interp* tcl_interp)
{
  // Register SWIG-generated C commands (hello_ipl_cmd, etc.)
  Ipl_Init(tcl_interp);
  // Evaluate the Tcl wrappers defined in ipl.tcl.
  utl::evalTclInit(tcl_interp, ipl_tcl_inits);
}

}  // namespace ipl
